name: "CI: lint"

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get user information
        run: |
          {
            echo "MEGALINTER_UID=$(id -u)"
            echo "MEGALINTER_GID=$(id -g)"
            echo "MEGALINTER_USER=$(id -un)"
          } >> "$GITHUB_ENV"

      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter@9949bad031045f366be2467e00e8371a7328a2e2 # v10.1.0
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ github.token }}
          # new non-root user feature
          MEGALINTER_UID: ${{ env.MEGALINTER_UID }}
          MEGALINTER_GID: ${{ env.MEGALINTER_GID }}
          MEGALINTER_USER: ${{ env.MEGALINTER_USER }}
          # shfmt shall prefer 2 spaces to indent not tabs
          BASH_SHFMT_ARGUMENTS: -indent 2 -case-indent

  ensure-immutable-actions:
    name: Run ensure-immutable-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Ensure workflow actions use immutable refs
        uses: joshjohanning/ensure-immutable-actions@bc90ba67ffdea94121d930e649ba3d6219dcf275 # v2.7.0
        with:
          include-first-party: "true"
          write-job-summary: "on-failure-only"
